### ISSUE TITLE
Contstan.dart

### ISSUE THREAD

**Issue by isfreddy** [davidlutta/NewsWiz#1]
can you include constant file?

**Comment by davidlutta** [comment]
import 'package:flutter/material.dart';

const String kBaseUrl="https://newsapi.org/v2/everything?q=";
const String kApiKey = "&apiKey=";
const TextStyle kDisplayTextStyle2 = TextStyle(
    fontSize: 40.0,
    color: Colors.black,
    fontWeight: FontWeight.w700
);
const TextStyle kDisplayTextStyle = TextStyle(
    fontSize: 40.0,
    color: Colors.white,
    fontWeight: FontWeight.w700
);
const TextStyle kAuthorTextStyle = TextStyle(
    fontSize: 20.0,
    color: Colors.white,
    fontWeight: FontWeight.normal
);
const TextStyle kDescriptionTextStyle = TextStyle(
    fontSize: 15.0,
    color: Colors.white,
    fontWeight: FontWeight.normal
);

That's all the code in the file make sure to insert your own api key from newsapi.org
